version: "3.7"

services:
  savannah-api-init:
    build:
      context: ./SavannahAPI
    command: php firstrun.php 2>&1 | tee data/firstrun.log.txt
    working_dir: /var/www/html/server
    volumes:
      - type: volume
        source: savannah_data
        target: /var/www/html/server/data
      # - type: bind
      #   source: ./SavannahAPI/doc/FIRSTRUN
      #   target: /var/www/html/server/FIRSTRUN
      #   read_only: true

  savannah-api:
    build:
      context: ./SavannahAPI
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: savannah_data
        target: /var/www/html/server/data


  buildbot-master:
    build:
      context: ./octave-buildbot
      dockerfile: master/Dockerfile
    ports:
      - target: 8010
        published: 8010  # Buildbot master web interface
        protocol: tcp
        mode: host
      - target: 9989
        published: 9989  # Buildbot worker communication
        protocol: tcp
        mode: host
      - target: 22
        published: 9988  # Buildbot worker rsync file transfer
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: master_config
        target: /buildbot/master
      - type: volume
        source: master_data
        target: /buildbot/data
      - type: bind
        source: ./config/buildbot/master.cfg
        target: /buildbot/master/master.cfg
        read_only: true
      - type: bind
        source: ./config/buildbot/authorized_keys
        target: /root/.ssh/authorized_keys
        read_only: true

  web:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: master_data
        target: /usr/share/nginx/html/buildbot/data
        volume:
          nocopy: true
      - type: bind
        source: ./config/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true

volumes:
  master_config:
  master_data:
  worker_data:
  savannah_data:
